spring.data.mongodb.uri=mongodb+srv://galaya412:Kng06%402002@cluster0.tomnxfu.mongodb.net/pafUserDB?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=pafUserDB

server.port=8081

# Optional: Enable MongoDB query logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
